// Manual auth types (kept for backwards compatibility)
export * from './auth';

// Generated types from OpenAPI spec
// Note: Some types may be duplicated in './auth' - prefer using generated types for new code
export type {
  ObjectId,
  SortType,
  RenderMode,
  UserEntity,
  // Re-export all from generated except duplicates
  AccessLevel,
  BrandEntity,
  BooleanResult,
  ProductEntity,
  WarehouseType,
  CategoryEntity,
  CustomerEntity,
  WarehouseEntity,
  WarehouseStatus,
  AccessPermission,
  ApiGatewayEntity,
  UserEntityResult,
  BrandEntityResult,
  ShiftTemplateEntity,
  ProductEntityResult,
  CategoryEntityResult,
  CustomerEntityResult,
  WarehouseEntityResult,
  AdaptiveMonitoredValue,
  ApiGatewayEntityResult,
  AdaptiveRuleConfigEntity,
  AdminGlobalSettingEntity,
  StringObjectKeyValuePair,
  ShiftTemplateEntityResult,
  AdaptiveRuleConfigEntityResult,
  AdminGlobalSettingEntityResult,
  UserEntityBasePaginationResponse,
  BrandEntityBasePaginationResponse,
  ProductEntityBasePaginationResponse,
  CategoryEntityBasePaginationResponse,
  CustomerEntityBasePaginationResponse,
  WarehouseEntityBasePaginationResponse,
  ApiGatewayEntityBasePaginationResponse,
  ShiftTemplateEntityBasePaginationResponse,
  AdaptiveRuleConfigEntityBasePaginationResponse,
  AdminGlobalSettingEntityBasePaginationResponse,
} from './generated';
